# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: github              # must match <id> in pom.xml distributionManagement
        server-username: USERNAME      # GitHub username
        server-password: TOKEN

    - name: Clean target
      run: mvn -B clean

    - name: Build maven
      run: mvn -B package --file pom.xml

    - name: Debug build package
      run: ls -l target

    env:
      USERNAME: ${{ github.actor }}
      TOKEN: ${{ secrets.WORKFLOW_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: github              # must match <id> in pom.xml distributionManagement
        server-username: USERNAME      # GitHub username
        server-password: TOKEN

    - name: Debug build package
      run: ls -l target

    - name: Deploy maven package
      run: mvn -B deploy --file pom.xml

    env:
      USERNAME: ${{ github.actor }}
      TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
